In [8]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import curve_fit

def gaussian(x,a,b,c):
    return a*np.exp(-(x-b)**2/(2*c**2))

def fit_gaussian(counts):
    x = np.arange(len(counts))
    return curve_fit(gaussian,x,counts)

test_data = {'0000': 9, '0001': 11, '0010': 34, '0011': 79, '0100': 173, '0101': 313, '0110': 455, '0111': 611, '1000': 676, '1001': 625, '1010': 492, '1011': 318, '1100': 179, '1101': 79, '1110': 26, '1111': 16}
labels, counts = zip(*sorted(test_data.items()))


popt, pcov = fit_gaussian(counts)

plt.bar(labels,counts)

x = np.aran


[672.41117844   8.05311456   2.42740375] [[ 1.49177368e+01 -1.14116724e-05 -3.59306912e-02]
 [-1.14116724e-05  2.59155276e-04  9.13015191e-08]
 [-3.59306912e-02  9.13015191e-08  2.59450450e-04]]
